version: '3'
services:
  connector-malware-bazaar:
    image: custom-malware-bazaar:6.6.1
    environment:
      - OPENCTI_URL=http://host.docker.internal:4000
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=<RANDOM UUID4 value>
      - "CONNECTOR_NAME=MalwareBazaar"
      - MALWAREBAZAAR_USER_TOKEN=${MALWAREBAZAAR_USER_TOKEN}
      - CONNECTOR_LOG_LEVEL=error
      - MALWAREBAZAAR_API_URL=https://mb-api.abuse.ch/api/v1/
      - MALWAREBAZAAR_COOLDOWN_SECONDS=300 # Time to wait in seconds between subsequent requests
      - MALWAREBAZAAR_INCLUDE_TAGS=exe,dll,docm,docx,doc,xls,xlsx,xlsm,js # (Optional) Only download files if any tag matches. (Comma separated)
      - MALWAREBAZAAR_INCLUDE_REPORTERS= # (Optional) Only download files uploaded by these reporters. (Comma separated)
      - MALWAREBAZAAR_LABELS=malware-bazaar # (Optional) Labels to apply to uploaded Artifacts. (Comma separated)
      - MALWAREBAZAAR_LABELS_COLOR=#54483b # Color to use for labels
    restart: always
